version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
platform: Any CPU
build:
  verbosity: minimal
configuration: Release
install:
  - ps: (new-object Net.WebClient).DownloadString("https://raw.githubusercontent.com/unchase/Unchase.Dynamics365.Connectedservice/master/vsix.ps1") | iex
before_build:
  - ps: nuget restore src\Unchase.Dynamics365.ConnectedService.sln
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
build_script:
  - msbuild src\Unchase.Dynamics365.ConnectedService.sln /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
after_test:
  - ps: Vsix-PushArtifacts | Vsix-PublishToGallery
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: Unchase.Dynamics365.ConnectedService-v$(appveyor_build_version)
  auth_token:
    secure: __________________________________________________________
  repository: unchase/Unchase.Dynamics365.ConnectedService
  artifact: /.*\.vsix/
  force_update: true
  # on:
    #branch: master                # release from master branch only
    #appveyor_repo_tag: false       # deploy on tag push only
notifications:
- provider: Email
  to:
    - spiritkola@hotmail.com
  subject: 'Unchase.Dynamics365.ConnectedService - Build {{status}}'
  message: "Building complete, commitId = {{commitId}}"
  on_build_status_changed: true